sonar.projectKey=buildpad-ui
sonar.projectName=buildpad-ui
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/storybook-dist/**,**/*.min.js,**/playwright-report/**,**/test-results/**,**/tests/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.sourceEncoding=UTF-8
