sonar.projectKey=buildpad-ui
sonar.projectName=buildpad-ui
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/storybook-dist/**,**/*.min.js,**/playwright-report/**,**/test-results/**,**/tests/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,**/.storybook/**,**/*.stories.ts,**/*.stories.tsx,**/*.daas.stories.tsx,apps/docs/**
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=packages/cli/coverage/lcov.info,packages/hooks/coverage/lcov.info,packages/ui-collections/coverage/lcov.info,packages/ui-forms/coverage/lcov.info,packages/ui-users/coverage/lcov.info,packages/utils/coverage/lcov.info,packages/ui-form/coverage/lcov.info,packages/ui-interfaces/coverage/lcov.info,packages/mcp-server/coverage/lcov.info
