/**
 * Module Access Keys Page
 *
 * Registry of application capability flags (`daas_module_access_keys`) that
 * policies can grant — the second permission dimension alongside per-collection
 * CRUD. Keys registered here become togglable on the "Module-Level Access" tab
 * of each policy at /policies/[id].
 *
 * Visible to admins and to users with read permission on
 * `daas_module_access_keys`.
 *
 * Generated by @buildpad/cli
 */

"use client";

import React from 'react';
import { ModuleAccessKeysManager } from '@/components/ui/users-management';

export default function ModuleAccessKeysPage() {
  return <ModuleAccessKeysManager />;
}
